-- MySQL Script generated by MySQL Workbench
-- dim. 13 nov. 2022 09:19:46
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`etudiant`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`etudiant` (
  `id` INT NOT NULL,
  `prenom` VARCHAR(255) NULL,
  `nom` VARCHAR(255) NULL,
  `naissance` DATE NULL,
  `sexe` VARCHAR(25) NULL,
  `email` VARCHAR(255) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`etage`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`etage` (
  `id` INT NOT NULL,
  `nom` VARCHAR(255) NULL,
  `numero` INT NULL,
  `superficie` INT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`salles`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`salles` (
  `id` INT NOT NULL,
  `nom` VARCHAR(255) NULL,
  `id_etage` INT NULL,
  `capacite` INT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
